//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLayer
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/ModelLayer")]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ModelLayer.Battle[] BattlesField;
        
        private System.DateTime BirthDateField;
        
        private string CountryField;
        
        private string EmailField;
        
        private ModelLayer.Units.Group[] GarisonField;
        
        private ModelLayer.User[] InvadersField;
        
        private int LevelField;
        
        private ModelLayer.Map MapField;
        
        private string NameField;
        
        private string PasswordField;
        
        private int RankingField;
        
        private string SessionField;
        
        private ModelLayer.Upgrades UpgradesField;
        
        private int UserIDField;
        
        private string UsernameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ModelLayer.Battle[] Battles
        {
            get
            {
                return this.BattlesField;
            }
            set
            {
                this.BattlesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BirthDate
        {
            get
            {
                return this.BirthDateField;
            }
            set
            {
                this.BirthDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ModelLayer.Units.Group[] Garison
        {
            get
            {
                return this.GarisonField;
            }
            set
            {
                this.GarisonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ModelLayer.User[] Invaders
        {
            get
            {
                return this.InvadersField;
            }
            set
            {
                this.InvadersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Level
        {
            get
            {
                return this.LevelField;
            }
            set
            {
                this.LevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ModelLayer.Map Map
        {
            get
            {
                return this.MapField;
            }
            set
            {
                this.MapField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Ranking
        {
            get
            {
                return this.RankingField;
            }
            set
            {
                this.RankingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Session
        {
            get
            {
                return this.SessionField;
            }
            set
            {
                this.SessionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ModelLayer.Upgrades Upgrades
        {
            get
            {
                return this.UpgradesField;
            }
            set
            {
                this.UpgradesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Map", Namespace="http://schemas.datacontract.org/2004/07/ModelLayer")]
    public partial class Map : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Upgrades", Namespace="http://schemas.datacontract.org/2004/07/ModelLayer")]
    public partial class Upgrades : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Battle", Namespace="http://schemas.datacontract.org/2004/07/ModelLayer")]
    public partial class Battle : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int InvatedIDField;
        
        private int InvaterIDField;
        
        private string OutcomeField;
        
        private int PlunderedIronField;
        
        private int PlunderedWoodField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InvatedID
        {
            get
            {
                return this.InvatedIDField;
            }
            set
            {
                this.InvatedIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InvaterID
        {
            get
            {
                return this.InvaterIDField;
            }
            set
            {
                this.InvaterIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Outcome
        {
            get
            {
                return this.OutcomeField;
            }
            set
            {
                this.OutcomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlunderedIron
        {
            get
            {
                return this.PlunderedIronField;
            }
            set
            {
                this.PlunderedIronField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlunderedWood
        {
            get
            {
                return this.PlunderedWoodField;
            }
            set
            {
                this.PlunderedWoodField = value;
            }
        }
    }
}
namespace ModelLayer.Units
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Group", Namespace="http://schemas.datacontract.org/2004/07/ModelLayer.Units")]
    public partial class Group : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int unitCapField;
        
        private ModelLayer.Units.Unit[] unitsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int unitCap
        {
            get
            {
                return this.unitCapField;
            }
            set
            {
                this.unitCapField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ModelLayer.Units.Unit[] units
        {
            get
            {
                return this.unitsField;
            }
            set
            {
                this.unitsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Unit", Namespace="http://schemas.datacontract.org/2004/07/ModelLayer.Units")]
    public partial class Unit : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ArmorField;
        
        private int AttackSpeedField;
        
        private int DamageField;
        
        private int HitPointsField;
        
        private System.Drawing.Point LoactionField;
        
        private double RangeField;
        
        private double SpeedField;
        
        private int UnitSizeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Armor
        {
            get
            {
                return this.ArmorField;
            }
            set
            {
                this.ArmorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AttackSpeed
        {
            get
            {
                return this.AttackSpeedField;
            }
            set
            {
                this.AttackSpeedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Damage
        {
            get
            {
                return this.DamageField;
            }
            set
            {
                this.DamageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HitPoints
        {
            get
            {
                return this.HitPointsField;
            }
            set
            {
                this.HitPointsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Drawing.Point Loaction
        {
            get
            {
                return this.LoactionField;
            }
            set
            {
                this.LoactionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Range
        {
            get
            {
                return this.RangeField;
            }
            set
            {
                this.RangeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Speed
        {
            get
            {
                return this.SpeedField;
            }
            set
            {
                this.SpeedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UnitSize
        {
            get
            {
                return this.UnitSizeField;
            }
            set
            {
                this.UnitSizeField = value;
            }
        }
    }
}
namespace System.Drawing
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Point", Namespace="http://schemas.datacontract.org/2004/07/System.Drawing")]
    public partial struct Point : System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int xField;
        
        private int yField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int x
        {
            get
            {
                return this.xField;
            }
            set
            {
                this.xField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int y
        {
            get
            {
                return this.yField;
            }
            set
            {
                this.yField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IServerService")]
public interface IServerService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/ReturnNumber", ReplyAction="http://tempuri.org/IServerService/ReturnNumberResponse")]
    ModelLayer.User ReturnNumber();
    
    //[System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/ReturnNumber", ReplyAction="http://tempuri.org/IServerService/ReturnNumberResponse")]
    //System.Threading.Tasks.Task<ModelLayer.User> ReturnNumberAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/Login", ReplyAction="http://tempuri.org/IServerService/LoginResponse")]
    ModelLayer.User Login(ModelLayer.User user);
    
    //[System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/Login", ReplyAction="http://tempuri.org/IServerService/LoginResponse")]
    //System.Threading.Tasks.Task<ModelLayer.User> LoginAsync(ModelLayer.User user);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IServerServiceChannel : IServerService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ServerServiceClient : System.ServiceModel.ClientBase<IServerService>, IServerService
{
    
    public ServerServiceClient()
    {
    }
    
    public ServerServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ServerServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public ModelLayer.User ReturnNumber()
    {
        return base.Channel.ReturnNumber();
    }
    
    //public System.Threading.Tasks.Task<ModelLayer.User> ReturnNumberAsync()
    //{
    //    return base.Channel.ReturnNumberAsync();
    //}
    
    public ModelLayer.User Login(ModelLayer.User user)
    {
        return base.Channel.Login(user);
    }
    
    //public System.Threading.Tasks.Task<ModelLayer.User> LoginAsync(ModelLayer.User user)
    //{
    //    return base.Channel.LoginAsync(user);
    //}
}
